version: '3.3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ROOT_PASSWORD=7878
      - MYSQL_DATABASE=judge2
#    //docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d -p 3306:3306 mysql:latest
#  //docker-compose -f docker-compose.yaml up